 
name:               Aggregate
query:              aggr-list-info
object:             aggr

counters:
  aggr-info:
    - ^name                                   => aggr
    - ^^uuid
    - ^home-name                              => node
    - ^type                                   => type
    - ^state                                  => state
    - disk-count                              => raid_disk_count
    - plex-count                              => raid_plex_count
    - raid-size
    - volume-count                            => volume_count_flexvol
    - size-available                          => space_available
    - size-total                              => space_total
    - size-used                               => space_used
    - size-percentage-used                    => space_used_percent
    - aggregate-space-details:
      - aggregate-space-info:
        - aggregate-space:
          - fs-space-info:
            - fs-files-private-used               => inode_files_private_used
            - fs-files-total                      => inode_files_total
            - fs-files-used                       => inode_files_used
            - fs-inodefile-private-capacity       => inode_inodefile_private_capacity
            - fs-inodefile-public-capacity        => inode_inodefile_public_capacity
            - fs-maxfiles-available               => inode_maxfiles_available
            - fs-maxfiles-possible                => inode_maxfiles_possible
            - fs-maxfiles-used                    => inode_maxfiles_used
            - fs-percent-inode-used-capacity      => inode_used_percent
            - fs-hybrid-cache-size-total          => hybrid_cache_size
            - fs-total-reserved-space             => space_reserved        
            - fs-sis-percent-saved                => space_sis_saved_percent
            - fs-sis-saved-space                  => space_sis_saved
            - fs-sis-shared-space                 => space_sis_shared_count
        - snapshot-space:
          - snapshot-space-info:
            - snapshot-files-total                  => snapshot_files_total 
            - snapshot-files-used                   => snapshot_files_used
            - snapshot-maxfiles-available           => snapshot_maxfiles_available
            - snapshot-maxfiles-possible            => snapshot_maxfiles_possible
            - snapshot-maxfiles-used                => snapshot_maxfiles_used
            - snapshot-percent-inode-used-capacity  => snapshot_inode_used_percent
            - snapshot-percent-used-capacity        => snapshot_used_percent
            - snapshot-size-available               => snapshot_size_available
            - snapshot-size-total                   => snapshot_size_total
            - snapshot-size-used                    => snapshot_size_used

plugins:
  - Status:
    - status:
      label: state
      ok_value: online

export_options:
  graphite_leafs:
    - node.{node}.aggr.{aggr}
  instance_keys:
    - aggr
  instance_labels:
    - type
    - state
