
name:                       SystemNode
query:                      system-node-get-iter
object:                     node

reset_matrix_with_zeros:    True


counters:
  node-details-info:
    - cpu-busytime
#    - ^cpu-firmware-release
    - env-failed-fan-count                 => failed_fan
    - ^env-failed-fan-message               => failed_fan_message
    - env-failed-power-supply-count        => failed_power
    - ^env-failed-power-supply-message      => failed_power_message
    - ^env-over-temperature                 => over_temperature
#    - ^is-all-flash-optimized
#    - ^is-all-flash-select-optimized
#    - ^is-capacity-optimized
#    - ^is-cloud-optimized
#    - ^is-diff-svcs
#    - ^is-epsilon-node
#    - ^is-node-cluster-eligible
    - ^is-node-healthy                      => healthy
#    - ^is-perf-optimized
    - ^maximum-aggregate-size               => max_aggr_size
    - ^maximum-number-of-volumes            => max_vol_num
    - ^maximum-volume-size                  => max_vol_size
    - ^^node                                => node
    - ^node-location                        => location
    - ^node-model                           => model
#   - node-nvram-id
#   - node-owner
    - ^node-serial-number                   => serial
#    - ^node-storage-configuration          => storage_configuration
#    - node-system-id
    - node-uptime                           => uptime
#    - node-uuid
    - ^node-vendor                          => vendor
#    - nvram-battery-status
    - ^product-version                      => version
#    - sas2-sas3-mixed-stack-support

plugins:
  Node:
    type: data


export_options:
  exclude_instance_name: True
  graphite_leafs:
    - node.{node}
  include_keys:
    - node
  include_labels:
    - over_temperature
    - max_aggr_size
    - max_vol_size
    - max_vol_num
    - warnings
    - healthy
    - location
    - model
    - serial
    - uptime
    - vendor
    - version
