
name:                         SnapMirror
query:                        snapmirror-get-iter
object:                       snapmirror

counters:
  snapmirror-info:
    - break-failed-count
    - break-successful-count
    - ^destination-volume
    - ^destination-volume-node       => destination_node
    - ^destination-vserver
    - ^is-healthy                    => healthy
    - lag-time
    - last-transfer-duration
    - last-transfer-end-timestamp
    - last-transfer-size
    - ^last-transfer-type
    - newest-snapshot-timestamp
    - ^^relationship-id
    - ^relationship-status
    - ^relationship-type
    - ^relationship-group-type      => group_type
    - resync-failed-count
    - resync-successful-count
    - ^schedule
    - ^source-volume
    - ^source-vserver
    - ^source-node
    - total-transfer-bytes
    - total-transfer-time-secs
    - ^unhealthy-reason
    - update-failed-count
    - update-successful-count

plugins:
  - Snapmirror

export_options:
  instance_keys:
    - relationship_id
    - destination_volume
    - destination_node
    - destination_vserver
    - source_volume
    - source_vserver
    - source_node
  instance_labels:
    - healthy
    - unhealthy_reason
    - last_transfer_type
    - relationship_status
    - relationship_type
    - schedule
    - destination_node_limit
    - source_node_limit
    - group_type
  graphite_leafs:
    - node.{destination_node}.snapmirror.dest.{destination_volume}
    - node.{source_node}.snapmirror.src.{source_volume}
    - svm.{destination_vserver}.snapmirror.dest.{destination_volume}
    - svm.{source_vserver}.snapmirror.src.{source_volume}