
name:                     CIFSNode
query:                    cifs:node
object:                   node_cifs

counters:
  - instance_name            => node
  - cifs_op_count            => op_count
  - cifs_ops                 => ops
  - cifs_read_ops            => read_ops
  - cifs_write_ops           => write_ops
  - cifs_latency             => latency
  - cifs_read_latency        => read_latency
  - cifs_write_latency       => write_latency
  - connections
  - established_sessions
  - open_files
  - signed_sessions

export_options:
  instance_keys:
    - node
  graphite_leafs:
    - node.{node}.cifs

override:
  - cifs_op_count: rate
