name:                     HeadroomCPU
query:                    resource_headroom_cpu
object:                   headroom_cpu

counters:
  - instance_name
  - node_name              => node
  - current_latency
  - current_ops
  - current_utilization
  - optimal_point_latency
  - optimal_point_ops
  - optimal_point_utilization
  - optimal_point_confidence_factor
  - ewma_daily
  - ewma_hourly
  - ewma_monthly
  - ewma_weekly

export_options:
  instance_keys:
    - node
  graphite_leafs:
    - node.{node_name}.headroom.processor
