
name:                     NFSv3Node
query:                    nfsv3
object:                   node_nfs

global_labels:
  - nfsv: v3

counters:
  - instance_name          => node
  - nfsv3_ops              => ops
  - nfsv3_read_ops         => read_ops
  - nfsv3_write_ops        => write_ops
  - nfsv3_read_latency     => read_avg_latency
  - nfsv3_write_latency    => write_avg_latency
  - nfsv3_avg_op_latency   => latency

export_options:
  instance_keys:
    - nfsv
  graphite_leafs:
    - node.{node}.nfsv3

