
name:                     SystemNode
query:                    system
object:                   node

instance_key:             name

counters:
  - instance_name         => node
  - avg_processor_busy
  - cpu_elapsed_time
  - uptime
  - cifs_ops
  - nfs_ops
  - iscsi_ops
  - fcp_ops
  - disk_data_read
  - disk_data_written
  - hdd_data_read
  - hdd_data_written
  - ssd_data_read
  - ssd_data_written
  - net_data_recv
  - net_data_sent
  - fcp_data_recv
  - fcp_data_sent

export_options:
  require_instance_keys: False
  graphite_leafs:
    - node.{node}
