name:                     TokenManager
query:                    token_manager
object:                   token

instance_key:             name

counters:
  - instance_name
  - token_copy_success 
  - token_create_success
  - token_zero_success
  - token_copy_failure
  - token_create_failure
  - token_zero_failure
  - token_copy_bytes
  - token_create_bytes
  - token_zero_bytes

override:
 - token_copy_bytes: rate
 - token_create_bytes: rate
 - token_zero_bytes: rate

export_options:
  instance_keys:
    - token
  graphite_leafs:
    - node.{node}.msft_odx
