global:
  scrape_interval:     15s
  evaluation_interval: 30s
  external_labels:
    monitor: 'harvest'

# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            - 'localhost:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert_rules.yml'
    
scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'harvest'
  file_sd_configs:
    - files:
      - 'harvest_targets*.yml'

  static_configs:
